### PR TITLE
Update cranelift-04-17.md

### PR DESCRIPTION
**Pull request by fitzgen**

### CODE REVIEW

**Comment by fitzgen** [comment]
@bytecodealliance/tsc it seems like I can't self-approve to make this landable anymore. I don't think that was intended?

**Comment by tschneidereit** [comment]
@fitzgen as in, there's no big, green "approve" button in the interface for you? If so, that's probably a result of the change to require a review from `CODEOWNERS`, which is unfortunate. If you confirm, then I'll revert that change.

**Comment by fitzgen** [comment]
Yeah, the button to approve this PR is disabled for me.

**Comment by tschneidereit** [comment]
That's unfortunate :( I changed the setting—can you check if you can approve again?

**Comment by fitzgen** [comment]
Yep I can merge and approve now.

**Pull request merged**
